version: "3.2"

services:
  backend: 
    build:
      context: .
      dockerfile: ./Dockerfiledev
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    environment: 
      MONGO_URL: mongodb://db/open-reg
      SECRET: secret
      NODE_ENV: development
    depends_on:
      - db
  db:
    container_name: open-reg-db
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - ./volumes/mongodb:/data/db
      - ./volumes/mongodb_config:/data/configdb