version: '3'

services:
    mongo:
        image: mongo:latest
        container_name: 'open-reg-mongo'
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
        command: mongod --smallfiles
    postgres:
        image: postgres:latest
        container_name: 'open-reg-postgres'
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: open_reg
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    mongo:
    postgres:
