version: "3.2"

services:
  backend: 
    volumes:
      - .:/server
    command: ['yarn', 'start:dev']
    ports:
      - 3000:3000
    environment: 
      MONGO_URL:
      NODE_ENV: development
    depends_on:
      - db
  db:
    container_name: open-reg-db
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - ./volumes/mongodb:/data/db
      - ./volumes/mongodb_config:/data/configdb